// let a = { name: 'bob', id: 1, tag: '@bobiscool' }
// let b = { name: 'bob', id: 1, tag: '@bobiscool' }

// function compare(item1, item2, propAccesor) {
// 	let reflector = new Proxy({}, reflectionHandler)
// 	let propName = propAccesor(reflector)
// 	console.log(propName)
// 	return item1[propName] === item2[propName]
// }

// const reflectionHandler = {
// 	get: function (target, prop) {
// 		return prop
// 	}
// }

// let hey = compare(a, b, e => e.name)

// console.log(hey)

var bob = { name: 'bob', id: 1, tag: '@bobiscool' }

var reflector = new Proxy({}, {
	get: function (target, prop) {
		return prop
	}
})

function access(obj, proper) {
    return proper(obj)
}

console.time('proxy')

access(bob, e => e.name)
access(bob, e => e.id)
access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)
// access(bob, e => e.name)
// access(bob, e => e.id)
// access(bob, e => e.tag)

console.timeEnd('proxy')

function accessString(obj, prop) {
	return obj[prop]
}

console.time('string')

accessString(bob, 'name')
accessString(bob, 'id')
accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')
// accessString(bob, 'name')
// accessString(bob, 'id')
// accessString(bob, 'tag')

console.timeEnd('string')
